name: modis_env
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0=pyhd8ed1ab_1
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - blosc=1.21.6=hd145fbb_1
  - branca=0.8.1=pyhd8ed1ab_0
  - brotli-bin=1.1.0=h1c43f85_4
  - brotli-python=1.1.0=py310h79c4529_4
  - bzip2=1.0.8=hfdf4475_7
  - c-ares=1.34.5=hf13058a_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - comm=0.2.3=pyhe01879c_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - folium=0.20.0=pyhd8ed1ab_0
  - freetype=2.13.3=h694c41f_1
  - freexl=2.0.0=h3183152_2
  - geopandas=1.1.1=pyhd8ed1ab_0
  - geopandas-base=1.1.1=pyha770c72_0
  - geos=3.13.1=h502464c_0
  - geotiff=1.7.4=h88234f0_2
  - giflib=5.2.2=h10d778d_0
  - h2=4.3.0=pyhcf101f3_0
  - hdf4=4.2.15=h8138101_7
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=h120a0e1_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh92f572d_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - json-c=0.18=hc62ec3d_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - krb5=1.21.3=h37d8d59_0
  - lcms2=2.17=h72f5680_0
  - lerc=4.0.0=hcca01a6_1
  - libaec=1.1.4=ha6bc127_0
  - libarchive=3.8.1=gpl_h9912a37_100
  - libblas=3.9.0=35_h7f60823_openblas
  - libbrotlicommon=1.1.0=h1c43f85_4
  - libbrotlidec=1.1.0=h1c43f85_4
  - libbrotlienc=1.1.0=h1c43f85_4
  - libcblas=3.9.0=35_hff6cab4_openblas
  - libcurl=8.14.1=h5dec5d8_0
  - libcxx=21.1.0=h3d58e20_1
  - libdeflate=1.24=hcc1b750_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libev=4.33=h10d778d_2
  - libexpat=2.7.1=h21dd04a_0
  - libffi=3.4.6=h281671d_1
  - libfreetype=2.13.3=h694c41f_1
  - libfreetype6=2.13.3=h40dfd5c_1
  - libgdal-core=3.10.3=h55ca5b3_13
  - libgdal-hdf4=3.10.3=h8901399_13
  - libgfortran=15.1.0=h5f6db21_1
  - libgfortran5=15.1.0=hfa3c126_1
  - libiconv=1.18=h57a12c2_2
  - libjpeg-turbo=3.1.0=h6e16a3a_0
  - libkml=1.3.0=h9ee1731_1021
  - liblapack=3.9.0=35_h236ab99_openblas
  - liblzma=5.8.1=hd471939_2
  - libnghttp2=1.67.0=h3338091_0
  - libopenblas=0.3.30=openmp_h83c2472_2
  - libpng=1.6.50=h84aeda2_1
  - librttopo=1.1.0=hd2ea1e3_18
  - libsodium=1.0.20=hfdf4475_0
  - libspatialite=5.1.0=hf0eb338_14
  - libsqlite=3.50.4=h39a8b3b_0
  - libssh2=1.11.1=hed3591d_0
  - libtiff=4.7.0=h59ddb5d_6
  - libwebp-base=1.6.0=hb807250_0
  - libxcb=1.17.0=hf1f96e2_0
  - libxml2=2.13.8=he1bc88e_1
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=21.1.0=hf4e0ed4_0
  - lz4-c=1.10.0=h240833e_1
  - lzo=2.10=h4132b18_1002
  - mapclassify=2.8.1=pyhd8ed1ab_1
  - matplotlib-base=3.10.6=py310h2102b89_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - minizip=4.0.10=hfb7a1ec_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h0622a9a_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - openjpeg=2.5.3=h036ada5_1
  - openssl=3.5.2=h6e31bce_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.45=hf733adb_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyh8b19718_0
  - platformdirs=4.4.0=pyhcf101f3_0
  - proj=9.6.2=h8462e38_2
  - prompt-toolkit=3.0.52=pyha770c72_0
  - pthread-stubs=0.4=h00291cd_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhe01879c_2
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.18=h93e8a92_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h3c5361c_5
  - readline=8.2=h7cca4af_2
  - requests=2.32.5=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h25c286d_0
  - snuggs=1.4.7=pyhd8ed1ab_2
  - sqlite=3.50.4=h64b5abc_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=hf689a15_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - uriparser=0.9.8=h6aefe2f_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xerces-c=3.2.5=h197e74d_2
  - xorg-libxau=1.0.12=h6e16a3a_0
  - xorg-libxdmcp=1.1.5=h00291cd_0
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - zeromq=4.3.5=h5137e6a_8
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hd23fc13_2
  - zstd=1.5.7=h8210216_2
  - pip:
    - brotli==1.1.0
    - cffi==1.17.1
    - contourpy==1.3.2
    - debugpy==1.8.16
    - fiona==1.10.1
    - fonttools==4.59.2
    - gdal==3.10.3
    - kiwisolver==1.4.9
    - markupsafe==3.0.2
    - matplotlib==3.10.6
    - mpmath==1.3.0
    - numpy==2.2.6
    - pandas==2.3.2
    - patsy==1.0.1
    - pillow==11.3.0
    - psutil==7.0.0
    - pyogrio==0.11.0
    - pyproj==3.7.1
    - pyzmq==27.0.2
    - rasterio==1.4.3
    - rasterstats==0.20.0
    - scikit-learn==1.7.1
    - scipy==1.15.2
    - shapely==2.1.1
    - simplejson==3.20.1
    - statsmodels==0.14.5
    - tornado==6.5.2
    - unicodedata2==16.0.0
    - zstandard==0.24.0
prefix: /Users/lukevonkapff/opt/anaconda3/envs/modis_env
